# Generated by Django 4.1.7 on 2023-02-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefs', models.TextField(blank=True, default='')),
                ('last_sub', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(default='', max_length=10)),
                ('full_name', models.TextField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('u_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='front.user')),
                ('teams_max', models.PositiveIntegerField(default=0)),
                ('teams_min', models.PositiveIntegerField(default=0)),
                ('student_max', models.PositiveIntegerField(default=0)),
                ('students_min', models.PositiveIntegerField(default=0)),
                ('admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('key', models.CharField(editable=False, max_length=3, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('stds_pr_Team', models.PositiveIntegerField(default=0)),
                ('teams_max', models.PositiveIntegerField(default=0)),
                ('teams_min', models.PositiveIntegerField(default=0)),
                ('location', models.TextField(blank=True, default='')),
                ('available_to', models.TextField(default='')),
                ('hidden', models.BooleanField(default=False)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.user')),
                ('advisor_co', models.ManyToManyField(blank=True, null=True, related_name='co_advisors', to='front.teacher')),
                ('advisor_main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advisor', to='front.teacher')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('key', models.CharField(default='', max_length=5, primary_key=True, serialize=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='front.group')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='front.team')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='front.user')),
                ('std_type', models.CharField(default='', max_length=50)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belongs', to='front.group')),
            ],
        ),
    ]
