# Generated by Django 4.1.7 on 2023-03-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_rename_stds_pr_team_topic_cap_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='num_teams',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='topic',
            name='advisor_co',
        ),
        migrations.AlterField(
            model_name='topic',
            name='advisor_main',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='topic',
            name='advisor_co',
            field=models.TextField(default=''),
        ),
    ]
