# Generated by Django 4.1.7 on 2023-03-01 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_topic_num_topic_num_teams_remove_topic_advisor_co_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='num_teams',
        ),
    ]
