# Generated by Django 4.1.7 on 2023-03-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_remove_topic_num_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='email',
            field=models.TextField(default=''),
        ),
    ]
