# Generated by Django 4.1.7 on 2023-03-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_document_alter_group_last_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('stats', models.FilePathField()),
                ('sln', models.FilePathField()),
            ],
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
