# Generated by Django 4.1.7 on 2023-05-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_solution_delete_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='student_max',
            new_name='students_max',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='u_name',
            new_name='user',
        ),
    ]
